### ISSUE TITLE
ShareGPT4V inference code example failure

### ISSUE THREAD

**Issue by mmealman** [InternLM/InternLM-XComposer#115]
For ShareGPT4V the inference code example is failing at eval_model().

The code in question:

```python
from share4v.model.builder import load_pretrained_model
from share4v.mm_utils import get_model_name_from_path
from share4v.eval.run_share4v import eval_model

model_path = "Lin-Chen/ShareGPT4V-7B"
prompt = "What is the most common catchphrase of the character on the right?"
image_file = "examples/breaking_bad.png"

args = type('Args', (), {
    "model_path": model_path,
    "model_base": None,
    "model_name": get_model_name_from_path(model_path),
    "query": prompt,
    "conv_mode": None,
    "image_file": image_file,
    "sep": ",",
    "temperature": 0,
    "top_p": None,
    "num_beams": 1,
    "max_new_tokens": 512
})()

eval_model(args)
```

The error:

```bash
[2024-01-01 13:17:05,601] [INFO] [real_accelerator.py:161:get_accelerator] Setting ds_accelerator to cuda (auto detect)
Loading checkpoint shards: 100%|███████████████████████████████████████████████████████████████████████████████████| 2/2 [00:04<00:00,  2.18s/it]
Traceback (most recent call last):
  File "/home/mmealman/src/InternLM-XComposer/projects/ShareGPT4V/inference.py", line 23, in <module>
    eval_model(args)
  File "/home/mmealman/src/InternLM-XComposer/projects/ShareGPT4V/share4v/eval/run_share4v.py", line 62, in eval_model
    image_tensor = image_processor.preprocess(image, return_tensors='pt')[
AttributeError: 'NoneType' object has no attribute 'preprocess'
```

**Comment by AY-Liu** [comment]
In this file `share4v/model/builder.py`
Replace 121 line code with 
```python
if 'sharegpt4v' in model_name.lower():
```

**Comment by mmealman** [comment]
That worked. Thanks.
