### ISSUE TITLE
RuntimeError: "compute_indices_weights_cubic" not implemented for 'Half'

### ISSUE THREAD

**Issue by YushunXiang** [InternLM/InternLM-XComposer#141]
When I wanted to evaluate the InternLM-XComposer2-VL model, something went wrong.

```
Traceback (most recent call last):
  File "/SSD/xuyue/OCL_MiniGPTv2/train.py", line 105, in <module>
    main()
  File "/SSD/xuyue/OCL_MiniGPTv2/train.py", line 91, in main
    model = task.build_model(cfg)
  File "/SSD/xuyue/OCL_MiniGPTv2/minigpt4/tasks/base_task.py", line 35, in build_model
    return model_cls.from_config(model_config)
  File "/SSD/xuyue/OCL_MiniGPTv2/minigpt4/models/internlm_xcomposer.py", line 138, in from_config
    model = cls(
  File "/SSD/xuyue/OCL_MiniGPTv2/minigpt4/models/internlm_xcomposer.py", line 47, in __init__
    self.model, self.tokenizer = self.init_llm(
  File "/SSD/xuyue/OCL_MiniGPTv2/minigpt4/models/internlm_xcomposer.py", line 87, in init_llm
    model = AutoModelForCausalLM.from_pretrained(
  File "/home/xuyue/anaconda3/envs/minigpt4/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 561, in from_pretrained
    return model_class.from_pretrained(
  File "/home/xuyue/anaconda3/envs/minigpt4/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3596, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/xuyue/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-vl-7b/modeling_internlm_xcomposer2.py", line 67, in __init__
    self.vit = build_vision_tower()
  File "/home/xuyue/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-vl-7b/build_mlp.py", line 11, in build_vision_tower
    return CLIPVisionTower(vision_tower)
  File "/home/xuyue/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-vl-7b/build_mlp.py", line 59, in __init__
    self.resize_pos()
  File "/home/xuyue/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-vl-7b/build_mlp.py", line 88, in resize_pos
    pos_tokens = torch.nn.functional.interpolate(
  File "/home/xuyue/anaconda3/envs/minigpt4/lib/python3.9/site-packages/torch/nn/functional.py", line 4028, in interpolate
    return torch._C._nn.upsample_bicubic2d(input, output_size, align_corners, scale_factors)
RuntimeError: "compute_indices_weights_cubic" not implemented for 'Half'
```

The config of my model is:

```python
llm_model_path = 'internlm/internlm-xcomposer2-vl-7b'
model = AutoModelForCausalLM.from_pretrained(
    llm_model_path,
    torch_dtype=torch.float16,
    trust_remote_code=True
).cuda()
tokenizer = AutoTokenizer.from_pretrained(
    llm_model_path,
    trust_remote_code=True,
)
model.tokenizer = tokenizer
```

**Comment by anthonyyuan** [comment]
SAME

**Comment by anthonyyuan** [comment]
ckpt_path = "internlm-xcomposer2-7b"
tokenizer = AutoTokenizer.from_pretrained(ckpt_path, trust_remote_code=True)
model = AutoModelForCausalLM.from_pretrained(ckpt_path, torch_dtype=torch.float16,device_map="cuda", trust_remote_code=True).eval().cuda().half()

**Comment by anthonyyuan** [comment]
IT IS OK

**Comment by YushunXiang** [comment]
> ckpt_path = "internlm-xcomposer2-7b" tokenizer = AutoTokenizer.from_pretrained(ckpt_path, trust_remote_code=True) model = AutoModelForCausalLM.from_pretrained(ckpt_path, torch_dtype=torch.float16,device_map="cuda", trust_remote_code=True).eval().cuda().half()

Thank you!
