### ISSUE TITLE
多机推理bug

### ISSUE THREAD

**Issue by rexain** [InternLM/InternLM-XComposer#209]
同样的推理代码，使用`internlm-xcomposer2-vl`时正常运行，但是使用`internlm-xcomposer-vl`会报bug。麻烦您帮忙看一下！

Error log:
```shell
2024-03-07 19:58:55,750 - modelscope - INFO - PyTorch version 2.0.1+cu117 Found.
2024-03-07 19:58:55,751 - modelscope - INFO - Loading ast index from /home/huiyu/.cache/modelscope/ast_indexer
2024-03-07 19:58:55,942 - modelscope - INFO - Loading done! Current index file version is 1.12.0, with md5 54ca6976d2ab2c576365121b624d5ad2 and a total number of 964 components indexed
2024-03-07 19:58:56,749 - modelscope - WARNING - Using the master branch is fragile, please use it with caution!
2024-03-07 19:58:56,750 - modelscope - INFO - Use user-specified model revision: master
Init VIT ... Done
Init Perceive Sampler ... Done
Init InternLM ... Done
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████| 4/4 [00:59<00:00, 14.92s/it]
Traceback (most recent call last):
  File "/DATA/DATA1/renxiaoyu/202403_mllm/code/internlm-xcomposer-vl_inference.py", line 58, in <module>
    model = dispatch_model(model, device_map=device_map)
  File "/home/huiyu/.conda/envs/intern_clean/lib/python3.9/site-packages/accelerate/big_modeling.py", line 349, in dispatch_model
    check_device_map(model, device_map)
  File "/home/huiyu/.conda/envs/intern_clean/lib/python3.9/site-packages/accelerate/utils/modeling.py", line 1296, in check_device_map
    raise ValueError(
ValueError: The device_map provided does not give any device for the following parameters: query_tokens, flag_image_start, flag_image_end, visual_encoder.cls_token, visual_encoder.pos_embed, visual_encoder.patch_embed.proj.weight, visual_encoder.patch_embed.proj.bias, visual_encoder.blocks.0.norm1.weight, visual_encoder.blocks.0.norm1.bias, visual_encoder.blocks.0.attn.q_bias, visual_encoder.blocks.0.attn.v_bias, visual_encoder.blocks.0.attn.qkv.weight, visual_encoder.blocks.0.attn.proj.weight, visual_encoder.blocks.0.attn.proj.bias, visual_encoder.blocks.0.norm2.weight, visual_encoder.blocks.0.norm2.bias, visual_encoder.blocks.0.mlp.fc1.weight, visual_encoder.blocks.0.mlp.fc1.bias, visual_encoder.blocks.0.mlp.fc2.weight, visual_encoder.blocks.0.mlp.fc2.bias, visual_encoder.blocks.1.norm1.weight, visual_encoder.blocks.1.norm1.bias, visual_encoder.blocks.1.attn.q_bias, visual_encoder.blocks.1.attn.v_bias, visual_encoder.blocks.1.attn.qkv.weight, visual_encoder.blocks.1.attn.proj.weight, visual_encoder.blocks.1.attn.proj.bias, visual_encoder.blocks.1.norm2.weight, visual_encoder.blocks.1.norm2.bias, visual_encoder.blocks.1.mlp.fc1.weight, visual_encoder.blocks.1.mlp.fc1.bias, visual_encoder.blocks.1.mlp.fc2.weight, visual_encoder.blocks.1.mlp.fc2.bias, visual_encoder.blocks.2.norm1.weight, visual_encoder.blocks.2.norm1.bias, visual_encoder.blocks.2.attn.q_bias, visual_encoder.blocks.2.attn.v_bias, visual_encoder.blocks.2.attn.qkv.weight, visual_encoder.blocks.2.attn.proj.weight, visual_encoder.blocks.2.attn.proj.bias, visual_encoder.blocks.2.norm2.weight, visual_encoder.blocks.2.norm2.bias, visual_encoder.blocks.2.mlp.fc1.weight, visual_encoder.blocks.2.mlp.fc1.bias, visual_encoder.blocks.2.mlp.fc2.weight, visual_encoder.blocks.2.mlp.fc2.bias, visual_encoder.blocks.3.norm1.weight, visual_encoder.blocks.3.norm1.bias, visual_encoder.blocks.3.attn.q_bias, visual_encoder.blocks.3.attn.v_bias, visual_encoder.blocks.3.attn.qkv.weight, visual_encoder.blocks.3.attn.proj.weight, visual_encoder.blocks.3.attn.proj.bias, visual_encoder.blocks.3.norm2.weight, visual_encoder.blocks.3.norm2.bias, visual_encoder.blocks.3.mlp.fc1.weight, visual_encoder.blocks.3.mlp.fc1.bias, visual_encoder.blocks.3.mlp.fc2.weight, visual_encoder.blocks.3.mlp.fc2.bias, visual_encoder.blocks.4.norm1.weight, visual_encoder.blocks.4.norm1.bias, visual_encoder.blocks.4.attn.q_bias, visual_encoder.blocks.4.attn.v_bias, visual_encoder.blocks.4.attn.qkv.weight, visual_encoder.blocks.4.attn.proj.weight, visual_encoder.blocks.4.attn.proj.bias, visual_encoder.blocks.4.norm2.weight, visual_encoder.blocks.4.norm2.bias, visual_encoder.blocks.4.mlp.fc1.weight, visual_encoder.blocks.4.mlp.fc1.bias, visual_encoder.blocks.4.mlp.fc2.weight, visual_encoder.blocks.4.mlp.fc2.bias, visual_encoder.blocks.5.norm1.weight, visual_encoder.blocks.5.norm1.bias, visual_encoder.blocks.5.attn.q_bias, visual_encoder.blocks.5.attn.v_bias, visual_encoder.blocks.5.attn.qkv.weight, visual_encoder.blocks.5.attn.proj.weight, visual_encoder.blocks.5.attn.proj.bias, visual_encoder.blocks.5.norm2.weight, visual_encoder.blocks.5.norm2.bias, visual_encoder.blocks.5.mlp.fc1.weight, visual_encoder.blocks.5.mlp.fc1.bias, visual_encoder.blocks.5.mlp.fc2.weight, visual_encoder.blocks.5.mlp.fc2.bias, visual_encoder.blocks.6.norm1.weight, visual_encoder.blocks.6.norm1.bias, visual_encoder.blocks.6.attn.q_bias, visual_encoder.blocks.6.attn.v_bias, visual_encoder.blocks.6.attn.qkv.weight, visual_encoder.blocks.6.attn.proj.weight, visual_encoder.blocks.6.attn.proj.bias, visual_encoder.blocks.6.norm2.weight, visual_encoder.blocks.6.norm2.bias, visual_encoder.blocks.6.mlp.fc1.weight, visual_encoder.blocks.6.mlp.fc1.bias, visual_encoder.blocks.6.mlp.fc2.weight, visual_encoder.blocks.6.mlp.fc2.bias, visual_encoder.blocks.7.norm1.weight, visual_encoder.blocks.7.norm1.bias, visual_encoder.blocks.7.attn.q_bias, visual_encoder.blocks.7.attn.v_bias, visual_encoder.blocks.7.attn.qkv.weight, visual_encoder.blocks.7.attn.proj.weight, visual_encoder.blocks.7.attn.proj.bias, visual_encoder.blocks.7.norm2.weight, visual_encoder.blocks.7.norm2.bias, visual_encoder.blocks.7.mlp.fc1.weight, visual_encoder.blocks.7.mlp.fc1.bias, visual_encoder.blocks.7.mlp.fc2.weight, visual_encoder.blocks.7.mlp.fc2.bias, visual_encoder.blocks.8.norm1.weight, visual_encoder.blocks.8.norm1.bias, visual_encoder.blocks.8.attn.q_bias, visual_encoder.blocks.8.attn.v_bias, visual_encoder.blocks.8.attn.qkv.weight, visual_encoder.blocks.8.attn.proj.weight, visual_encoder.blocks.8.attn.proj.bias, visual_encoder.blocks.8.norm2.weight, visual_encoder.blocks.8.norm2.bias, visual_encoder.blocks.8.mlp.fc1.weight, visual_encoder.blocks.8.mlp.fc1.bias, visual_encoder.blocks.8.mlp.fc2.weight, visual_encoder.blocks.8.mlp.fc2.bias, visual_encoder.blocks.9.norm1.weight, visual_encoder.blocks.9.norm1.bias, visual_encoder.blocks.9.attn.q_bias, visual_encoder.blocks.9.attn.v_bias, visual_encoder.blocks.9.attn.qkv.weight, visual_encoder.blocks.9.attn.proj.weight, visual_encoder.blocks.9.attn.proj.bias, visual_encoder.blocks.9.norm2.weight, visual_encoder.blocks.9.norm2.bias, visual_encoder.blocks.9.mlp.fc1.weight, visual_encoder.blocks.9.mlp.fc1.bias, visual_encoder.blocks.9.mlp.fc2.weight, visual_encoder.blocks.9.mlp.fc2.bias, visual_encoder.blocks.10.norm1.weight, visual_encoder.blocks.10.norm1.bias, visual_encoder.blocks.10.attn.q_bias, visual_encoder.blocks.10.attn.v_bias, visual_encoder.blocks.10.attn.qkv.weight, visual_encoder.blocks.10.attn.proj.weight, visual_encoder.blocks.10.attn.proj.bias, visual_encoder.blocks.10.norm2.weight, visual_encoder.blocks.10.norm2.bias, visual_encoder.blocks.10.mlp.fc1.weight, visual_encoder.blocks.10.mlp.fc1.bias, visual_encoder.blocks.10.mlp.fc2.weight, visual_encoder.blocks.10.mlp.fc2.bias, visual_encoder.blocks.11.norm1.weight, visual_encoder.blocks.11.norm1.bias, visual_encoder.blocks.11.attn.q_bias, visual_encoder.blocks.11.attn.v_bias, visual_encoder.blocks.11.attn.qkv.weight, visual_encoder.blocks.11.attn.proj.weight, visual_encoder.blocks.11.attn.proj.bias, visual_encoder.blocks.11.norm2.weight, visual_encoder.blocks.11.norm2.bias, visual_encoder.blocks.11.mlp.fc1.weight, visual_encoder.blocks.11.mlp.fc1.bias, visual_encoder.blocks.11.mlp.fc2.weight, visual_encoder.blocks.11.mlp.fc2.bias, visual_encoder.blocks.12.norm1.weight, visual_encoder.blocks.12.norm1.bias, visual_encoder.blocks.12.attn.q_bias, visual_encoder.blocks.12.attn.v_bias, visual_encoder.blocks.12.attn.qkv.weight, visual_encoder.blocks.12.attn.proj.weight, visual_encoder.blocks.12.attn.proj.bias, visual_encoder.blocks.12.norm2.weight, visual_encoder.blocks.12.norm2.bias, visual_encoder.blocks.12.mlp.fc1.weight, visual_encoder.blocks.12.mlp.fc1.bias, visual_encoder.blocks.12.mlp.fc2.weight, visual_encoder.blocks.12.mlp.fc2.bias, visual_encoder.blocks.13.norm1.weight, visual_encoder.blocks.13.norm1.bias, visual_encoder.blocks.13.attn.q_bias, visual_encoder.blocks.13.attn.v_bias, visual_encoder.blocks.13.attn.qkv.weight, visual_encoder.blocks.13.attn.proj.weight, visual_encoder.blocks.13.attn.proj.bias, visual_encoder.blocks.13.norm2.weight, visual_encoder.blocks.13.norm2.bias, visual_encoder.blocks.13.mlp.fc1.weight, visual_encoder.blocks.13.mlp.fc1.bias, visual_encoder.blocks.13.mlp.fc2.weight, visual_encoder.blocks.13.mlp.fc2.bias, visual_encoder.blocks.14.norm1.weight, visual_encoder.blocks.14.norm1.bias, visual_encoder.blocks.14.attn.q_bias, visual_encoder.blocks.14.attn.v_bias, visual_encoder.blocks.14.attn.qkv.weight, visual_encoder.blocks.14.attn.proj.weight, visual_encoder.blocks.14.attn.proj.bias, visual_encoder.blocks.14.norm2.weight, visual_encoder.blocks.14.norm2.bias, visual_encoder.blocks.14.mlp.fc1.weight, visual_encoder.blocks.14.mlp.fc1.bias, visual_encoder.blocks.14.mlp.fc2.weight, visual_encoder.blocks.14.mlp.fc2.bias, visual_encoder.blocks.15.norm1.weight, visual_encoder.blocks.15.norm1.bias, visual_encoder.blocks.15.attn.q_bias, visual_encoder.blocks.15.attn.v_bias, visual_encoder.blocks.15.attn.qkv.weight, visual_encoder.blocks.15.attn.proj.weight, visual_encoder.blocks.15.attn.proj.bias, visual_encoder.blocks.15.norm2.weight, visual_encoder.blocks.15.norm2.bias, visual_encoder.blocks.15.mlp.fc1.weight, visual_encoder.blocks.15.mlp.fc1.bias, visual_encoder.blocks.15.mlp.fc2.weight, visual_encoder.blocks.15.mlp.fc2.bias, visual_encoder.blocks.16.norm1.weight, visual_encoder.blocks.16.norm1.bias, visual_encoder.blocks.16.attn.q_bias, visual_encoder.blocks.16.attn.v_bias, visual_encoder.blocks.16.attn.qkv.weight, visual_encoder.blocks.16.attn.proj.weight, visual_encoder.blocks.16.attn.proj.bias, visual_encoder.blocks.16.norm2.weight, visual_encoder.blocks.16.norm2.bias, visual_encoder.blocks.16.mlp.fc1.weight, visual_encoder.blocks.16.mlp.fc1.bias, visual_encoder.blocks.16.mlp.fc2.weight, visual_encoder.blocks.16.mlp.fc2.bias, visual_encoder.blocks.17.norm1.weight, visual_encoder.blocks.17.norm1.bias, visual_encoder.blocks.17.attn.q_bias, visual_encoder.blocks.17.attn.v_bias, visual_encoder.blocks.17.attn.qkv.weight, visual_encoder.blocks.17.attn.proj.weight, visual_encoder.blocks.17.attn.proj.bias, visual_encoder.blocks.17.norm2.weight, visual_encoder.blocks.17.norm2.bias, visual_encoder.blocks.17.mlp.fc1.weight, visual_encoder.blocks.17.mlp.fc1.bias, visual_encoder.blocks.17.mlp.fc2.weight, visual_encoder.blocks.17.mlp.fc2.bias, visual_encoder.blocks.18.norm1.weight, visual_encoder.blocks.18.norm1.bias, visual_encoder.blocks.18.attn.q_bias, visual_encoder.blocks.18.attn.v_bias, visual_encoder.blocks.18.attn.qkv.weight, visual_encoder.blocks.18.attn.proj.weight, visual_encoder.blocks.18.attn.proj.bias, visual_encoder.blocks.18.norm2.weight, visual_encoder.blocks.18.norm2.bias, visual_encoder.blocks.18.mlp.fc1.weight, visual_encoder.blocks.18.mlp.fc1.bias, visual_encoder.blocks.18.mlp.fc2.weight, visual_encoder.blocks.18.mlp.fc2.bias, visual_encoder.blocks.19.norm1.weight, visual_encoder.blocks.19.norm1.bias, visual_encoder.blocks.19.attn.q_bias, visual_encoder.blocks.19.attn.v_bias, visual_encoder.blocks.19.attn.qkv.weight, visual_encoder.blocks.19.attn.proj.weight, visual_encoder.blocks.19.attn.proj.bias, visual_encoder.blocks.19.norm2.weight, visual_encoder.blocks.19.norm2.bias, visual_encoder.blocks.19.mlp.fc1.weight, visual_encoder.blocks.19.mlp.fc1.bias, visual_encoder.blocks.19.mlp.fc2.weight, visual_encoder.blocks.19.mlp.fc2.bias, visual_encoder.blocks.20.norm1.weight, visual_encoder.blocks.20.norm1.bias, visual_encoder.blocks.20.attn.q_bias, visual_encoder.blocks.20.attn.v_bias, visual_encoder.blocks.20.attn.qkv.weight, visual_encoder.blocks.20.attn.proj.weight, visual_encoder.blocks.20.attn.proj.bias, visual_encoder.blocks.20.norm2.weight, visual_encoder.blocks.20.norm2.bias, visual_encoder.blocks.20.mlp.fc1.weight, visual_encoder.blocks.20.mlp.fc1.bias, visual_encoder.blocks.20.mlp.fc2.weight, visual_encoder.blocks.20.mlp.fc2.bias, visual_encoder.blocks.21.norm1.weight, visual_encoder.blocks.21.norm1.bias, visual_encoder.blocks.21.attn.q_bias, visual_encoder.blocks.21.attn.v_bias, visual_encoder.blocks.21.attn.qkv.weight, visual_encoder.blocks.21.attn.proj.weight, visual_encoder.blocks.21.attn.proj.bias, visual_encoder.blocks.21.norm2.weight, visual_encoder.blocks.21.norm2.bias, visual_encoder.blocks.21.mlp.fc1.weight, visual_encoder.blocks.21.mlp.fc1.bias, visual_encoder.blocks.21.mlp.fc2.weight, visual_encoder.blocks.21.mlp.fc2.bias, visual_encoder.blocks.22.norm1.weight, visual_encoder.blocks.22.norm1.bias, visual_encoder.blocks.22.attn.q_bias, visual_encoder.blocks.22.attn.v_bias, visual_encoder.blocks.22.attn.qkv.weight, visual_encoder.blocks.22.attn.proj.weight, visual_encoder.blocks.22.attn.proj.bias, visual_encoder.blocks.22.norm2.weight, visual_encoder.blocks.22.norm2.bias, visual_encoder.blocks.22.mlp.fc1.weight, visual_encoder.blocks.22.mlp.fc1.bias, visual_encoder.blocks.22.mlp.fc2.weight, visual_encoder.blocks.22.mlp.fc2.bias, visual_encoder.blocks.23.norm1.weight, visual_encoder.blocks.23.norm1.bias, visual_encoder.blocks.23.attn.q_bias, visual_encoder.blocks.23.attn.v_bias, visual_encoder.blocks.23.attn.qkv.weight, visual_encoder.blocks.23.attn.proj.weight, visual_encoder.blocks.23.attn.proj.bias, visual_encoder.blocks.23.norm2.weight, visual_encoder.blocks.23.norm2.bias, visual_encoder.blocks.23.mlp.fc1.weight, visual_encoder.blocks.23.mlp.fc1.bias, visual_encoder.blocks.23.mlp.fc2.weight, visual_encoder.blocks.23.mlp.fc2.bias, visual_encoder.blocks.24.norm1.weight, visual_encoder.blocks.24.norm1.bias, visual_encoder.blocks.24.attn.q_bias, visual_encoder.blocks.24.attn.v_bias, visual_encoder.blocks.24.attn.qkv.weight, visual_encoder.blocks.24.attn.proj.weight, visual_encoder.blocks.24.attn.proj.bias, visual_encoder.blocks.24.norm2.weight, visual_encoder.blocks.24.norm2.bias, visual_encoder.blocks.24.mlp.fc1.weight, visual_encoder.blocks.24.mlp.fc1.bias, visual_encoder.blocks.24.mlp.fc2.weight, visual_encoder.blocks.24.mlp.fc2.bias, visual_encoder.blocks.25.norm1.weight, visual_encoder.blocks.25.norm1.bias, visual_encoder.blocks.25.attn.q_bias, visual_encoder.blocks.25.attn.v_bias, visual_encoder.blocks.25.attn.qkv.weight, visual_encoder.blocks.25.attn.proj.weight, visual_encoder.blocks.25.attn.proj.bias, visual_encoder.blocks.25.norm2.weight, visual_encoder.blocks.25.norm2.bias, visual_encoder.blocks.25.mlp.fc1.weight, visual_encoder.blocks.25.mlp.fc1.bias, visual_encoder.blocks.25.mlp.fc2.weight, visual_encoder.blocks.25.mlp.fc2.bias, visual_encoder.blocks.26.norm1.weight, visual_encoder.blocks.26.norm1.bias, visual_encoder.blocks.26.attn.q_bias, visual_encoder.blocks.26.attn.v_bias, visual_encoder.blocks.26.attn.qkv.weight, visual_encoder.blocks.26.attn.proj.weight, 
```

推理代码:
```python
import torch
from modelscope import snapshot_download, AutoModel, AutoTokenizer
import argparse
import json

heatmap = []
results = []
top = 300
result_file = "/DATA/DATA1/renxiaoyu/202403_mllm/results/td/internlm-xcomposer-vl.json" 
with open('/DATA/DATA1/renxiaoyu/202403_mllm/data/heatmap_td_list.txt', 'r', encoding='utf-8') as f:
    for ann in f.readlines():
        ann = ann.strip('\n')       #去除文本中的换行符
        heatmap.append(ann)


def auto_configure_device_map(num_gpus):
    # visual_encoder 算4层
    # internlm_model.model.embed_tokens 占用1层
    # norm 和 lm_head 占用1层
    # transformer.layers 占用 32 层
    # 总共34层分配到num_gpus张卡上
    num_trans_layers = 32
    per_gpu_layers = 38 / num_gpus

    device_map = {
        'vit': 0,
        'vision_proj': 0,
        'model.tok_embeddings': 0,
        'model.norm': num_gpus - 1,
        'output': num_gpus - 1,
    }

    used = 3
    gpu_target = 0
    for i in range(num_trans_layers):
        if used >= per_gpu_layers:
            gpu_target += 1
            used = 0
        assert gpu_target < num_gpus
        device_map[f'model.layers.{i}'] = gpu_target
        used += 1

    return device_map
    
    
torch.set_grad_enabled(False)
parser = argparse.ArgumentParser()
parser.add_argument("--num_gpus", default=2, type=int)
#parser.add_argument("--dtype", default='fp16', type=str)
args = parser.parse_args()

# init model and tokenizer
model_dir = snapshot_download('Shanghai_AI_Laboratory/internlm-xcomposer-vl-7b', revision='master')
model = AutoModel.from_pretrained(model_dir, trust_remote_code=True).cuda().eval()
if args.num_gpus > 1:
    from accelerate import dispatch_model
    device_map = auto_configure_device_map(args.num_gpus)
    model = dispatch_model(model, device_map=device_map)

tokenizer = AutoTokenizer.from_pretrained(model_dir, trust_remote_code=True)
#model.tokenizer = tokenizer

text = "<ImageHere> xx."

with torch.cuda.amp.autocast():
    for idx in range(top):
        image = heatmap[idx]
        response, _ = model.chat(tokenizer, query=text, image=image, history=[], do_sample=False)
        print(response)
        results.append({"image": image, "Answer": response})

with open (result_file, 'w') as f:
    json.dump(results, f, ensure_ascii=True, indent = 4)
```

**Comment by rexain** [comment]
事实上，`internlm-xcomposer-vl`使用单机推理也会报错。
难道这个是text-to-text模型吗？
Error log:
```shell
2024-03-07 20:23:14,649 - modelscope - INFO - PyTorch version 2.0.1+cu117 Found.
2024-03-07 20:23:14,650 - modelscope - INFO - Loading ast index from /home/huiyu/.cache/modelscope/ast_indexer
2024-03-07 20:23:14,855 - modelscope - INFO - Loading done! Current index file version is 1.12.0, with md5 54ca6976d2ab2c576365121b624d5ad2 and a total number of 964 components indexed
2024-03-07 20:23:15,635 - modelscope - WARNING - Using the master branch is fragile, please use it with caution!
2024-03-07 20:23:15,635 - modelscope - INFO - Use user-specified model revision: master
Init VIT ... Done
Init Perceive Sampler ... Done
Init InternLM ... Done
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████| 4/4 [00:25<00:00,  6.49s/it]
Traceback (most recent call last):
  File "/DATA/DATA1/renxiaoyu/202403_mllm/code/internlm-xcomposer-vl_inference.py", line 26, in <module>
    response, _ = model.chat(tokenizer, query=text, image=image, history=[], do_sample=False)
  File "/home/huiyu/.cache/huggingface/modules/transformers_modules/internlm-xcomposer-vl-7b/modeling_InternLM_XComposer.py", line 213, in chat
    text_embeds = self.encode_text(text)
  File "/home/huiyu/.cache/huggingface/modules/transformers_modules/internlm-xcomposer-vl-7b/modeling_InternLM_XComposer.py", line 176, in encode_text
    text_token_ids = self.tokenizer(
  File "/home/huiyu/.conda/envs/intern_clean/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2602, in __call__
    encodings = self._call_one(text=text, text_pair=text_pair, **all_kwargs)
  File "/home/huiyu/.conda/envs/intern_clean/lib/python3.9/site-packages/transformers/tokenization_utils_base.py", line 2660, in _call_one
    raise ValueError(
ValueError: text input must of type `str` (single example), `List[str]` (batch or single pretokenized example) or `List[List[str]]` (batch of pretokenized examples).
```

**Comment by LightDXY** [comment]
hi，xcomposer1 和xcomposer2由于模型结构不同，auto_configure_device_map需要处理的参数不同，1.0可以参考https://github.com/InternLM/InternLM-XComposer/blob/main/InternLM-XComposer-1.0/examples/example_chat.py

**Comment by Cloopen-ReLiNK** [comment]
> hi，xcomposer1 和xcomposer2由于模型结构不同，auto_configure_device_map需要处理的参数不同，1.0可以参考https://github.com/InternLM/InternLM-XComposer/blob/main/InternLM-XComposer-1.0/examples/example_chat.py

@LightDXY  xcomposer2-4khd 应该怎么设置呢
