### ISSUE TITLE
微调使用zero3在载入vision_tower出现报错，当前是不支持zero3吗？

### ISSUE THREAD

**Issue by shaoyan1223** [InternLM/InternLM-XComposer#237]
Traceback (most recent call last):
  File "/opt/tiger/internlm-xcomposer/finetune/finetune.py", line 311, in <module>
    train()
  File "/opt/tiger/internlm-xcomposer/finetune/finetune.py", line 242, in train
    model = transformers.AutoModelForCausalLM.from_pretrained(
  File "/home/tiger/.local/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 479, in from_pretrained
    return model_class.from_pretrained(
  File "/home/tiger/.local/lib/python3.9/site-packages/transformers/modeling_utils.py", line 2675, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/usr/local/lib/python3.9/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    f(module, *args, **kwargs)
  File "/home/tiger/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-vl-7b/modeling_internlm_xcomposer2.py", line 67, in __init__
    self.vit = build_vision_tower()
  File "/home/tiger/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-vl-7b/build_mlp.py", line 12, in build_vision_tower
    return CLIPVisionTower(vision_tower)
  File "/usr/local/lib/python3.9/dist-packages/deepspeed/runtime/zero/partition_parameters.py", line 385, in wrapper
    f(module, *args, **kwargs)
  File "/home/tiger/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-vl-7b/build_mlp.py", line 60, in __init__
    self.resize_pos()
  File "/home/tiger/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-vl-7b/build_mlp.py", line 91, in resize_pos
    pos_tokens = pos_tokens.reshape(-1, orig_size, orig_size,Traceback (most recent call last):

  File "/opt/tiger/internlm-xcomposer/finetune/finetune.py", line 311, in <module>
RuntimeError: cannot reshape tensor of 0 elements into shape [-1, 24, 24, 0] because the unspecified dimension size -1 can be any value and is ambiguous

**Comment by yuhangzang** [comment]
We didn't try zero-3 in our environment, so there may be some conflicts in the code.

**Comment by sxlyiyiyi** [comment]
> 回溯（最近一次调用最后一次）： 文件“/opt/tiger/internlm-xcomposer/finetune/finetune.py”，第 311 行，在 train() 文件“/opt/tiger/internlm-xcomposer/finetune/finetune.py”，第 242 行，在 train model = transformers.AutoModelForCausalLM.from_pretrained（ 文件“/home/tiger/.local/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py”，第 479 行，在 from_pretrained return model_class.from_pretrained（ 文件“/home/tiger/.local/lib/python3.9/site-packages/transformers/modeling_utils.py”，第 2675 行，在 from_pretrained model = cls（config，*model_args，**model_kwargs） 文件“/usr/local/lib/python3.9/dist-packages/deepspeed/runtime/zero/partition_parameters.py”，第 385 行，在包装器 f（module，* args，** kwargs） 文件“/home/tiger/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-vl-7b/modeling_internlm_xcomposer2.py”，第 67 行，在**init** self.vit = build_vision_tower（） 文件“/home/tiger/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-vl-7b/build_mlp.py”，第 12 行，在 build_vision_tower 中 返回 CLIPVisionTower（vision_tower） 文件“/usr/local/lib/python3.9/dist-packages/deepspeed/runtime/zero/partition_parameters.py”，行385，在包装器 f（module，* args，** kwargs）中 文件“/home/tiger/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-vl-7b/build_mlp.py”，第 60 行，在**init** self.resize_pos（） 中文件“/home/tiger/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-vl-7b/build_mlp.py”，第 91 行，在 resize_pos 中 pos_tokens = pos_tokens.reshape（-1，orig_size，orig_size，Traceback（最近一次调用最后一次）：
> 
> 文件“/opt/tiger/internlm-xcomposer/finetune/finetune.py”第 311 行， RuntimeError：无法将 0 个元素的张量重塑为形状 [-1, 24, 24, 0]，因为未指定的维度大小 -1 可以是任何值并且不明确

现在可以用zero3训练了吗

**Comment by bang123-box** [comment]
还是不可以
