### ISSUE TITLE
No module named 'transformers_modules.internlm/internlm-xcomposer-7b'

### ISSUE THREAD

**Issue by walkskysu** [InternLM/InternLM-XComposer#25]
下了internlm-xcomposer-7b ，放到internlm/internlm-xcomposer-7b、但是有下列报错

PS E:\InternLM-XComposer> python .\examples\web_demo.py
Traceback (most recent call last):
  File "E:\cnai\InternLM-XComposer\examples\web_demo.py", line 816, in <module>
    demo_ui = Demo_UI()
  File "E:\cnai\InternLM-XComposer\examples\web_demo.py", line 47, in __init__
    self.llm_model = AutoModel.from_pretrained(
  File "C:\Python\Python310\lib\site-packages\transformers\models\auto\auto_factory.py", line 456, in from_pretrained
    config, kwargs = AutoConfig.from_pretrained(
  File "C:\Python\Python310\lib\site-packages\transformers\models\auto\configuration_auto.py", line 953, in from_pretrained
    config_class = get_class_from_dynamic_module(class_ref, pretrained_model_name_or_path, **kwargs)
  File "C:\Python\Python310\lib\site-packages\transformers\dynamic_module_utils.py", line 443, in get_class_from_dynamic_module
    return get_class_in_module(class_name, final_module.replace(".py", ""))
  File "C:\Python\Python310\lib\site-packages\transformers\dynamic_module_utils.py", line 164, in get_class_in_module
    module = importlib.import_module(module_path)
  File "C:\Python\Python310\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 992, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1050, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1027, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1004, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'transformers_modules.internlm/internlm-xcomposer-7b'

**Comment by vansin** [comment]
代码是?

**Comment by vansin** [comment]
web_demo.py 改了哪呢？
具体贴一下完整代码

**Comment by walkskysu** [comment]
问题找到了，在web_demo.py windows下路径要由 internlm/internlm-xcomposer-7b  改为 'internlm\internlm-xcomposer-7b
路径符号不一致
        self.llm_model = AutoModel.from_pretrained(
            'internlm\internlm-xcomposer-7b', trust_remote_code=True)
        tokenizer = AutoTokenizer.from_pretrained(
            'internlm\internlm-xcomposer-7b', trust_remote_code=True)
