### ISSUE TITLE
运行web_demo.py 出现错误

### ISSUE THREAD

**Issue by WeiXuanLi-1024** [InternLM/InternLM-XComposer#28]
下载的是最新的代码文件，运行时出现如下错误：
正在接受医生的检查，医生在为它量体温。', 10: '一只宠物狗在主人帮助下清理自己的粪便，主人在旁边指导。', 12: '一只宠物狗在主人帮助下处理自己的毛发，主人在旁边指导。'}
https://static.openxlab.org.cn/lingbi/jpg-images/61ec717e9ee8ffd984f79d01838de29e352b6aa9b9a04bb60e56a92f00fa72db.jpg
download image with url
image downloaded
https://static.openxlab.org.cn/lingbi/jpg-images/78668d1138f169a78284213bb2df7991cf77ff48bbdb6f938a3536d238ccbdc7.jpg
download image with url
image downloaded
https://static.openxlab.org.cn/lingbi/jpg-images/9db1b1ecdfc698526459d4bb519ebd1dfc3b9be9e4983ff8b862dd970257793a.jpg
download image with url
image downloaded
https://static.openxlab.org.cn/lingbi/jpg-images/2f3ce59b613d2b7b989a919819ef1aed67dcd56d6381b0ea2af68972c700c367.jpg
download image with url
image downloaded
https://static.openxlab.org.cn/lingbi/jpg-images/3e4914997caf27f88b1219070586a7aa9ce79c6afacf824a640396abab216230.jpg
download image with url
image downloaded
https://static.openxlab.org.cn/lingbi/jpg-images/41eb2c71b25921e4ccb423df6e402caf74d71bc981b9bd699a44bc2d66ec0524.jpg
download image with url
image downloaded
model_select_image
Traceback (most recent call last):
  File "/home/enbo/anaconda3/envs/llama2-accessory/lib/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/home/enbo/anaconda3/envs/llama2-accessory/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/home/enbo/anaconda3/envs/llama2-accessory/lib/python3.10/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/home/enbo/anaconda3/envs/llama2-accessory/lib/python3.10/site-packages/gradio/blocks.py", line 1123, in call_function
    prediction = await utils.async_iteration(iterator)
  File "/home/enbo/anaconda3/envs/llama2-accessory/lib/python3.10/site-packages/gradio/utils.py", line 512, in async_iteration
    return await iterator.__anext__()
  File "/home/enbo/anaconda3/envs/llama2-accessory/lib/python3.10/site-packages/gradio/utils.py", line 505, in __anext__
    return await anyio.to_thread.run_sync(
  File "/home/enbo/anaconda3/envs/llama2-accessory/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/home/enbo/anaconda3/envs/llama2-accessory/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/home/enbo/anaconda3/envs/llama2-accessory/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/home/enbo/anaconda3/envs/llama2-accessory/lib/python3.10/site-packages/gradio/utils.py", line 488, in run_sync_iterator_async
    return next(iterator)
  File "/home/enbo/anaconda3/envs/llama2-accessory/lib/python3.10/site-packages/gradio/utils.py", line 638, in gen_wrapper
    yield from f(*args, **kwargs)
  File "/data/liwx/InternLM-XComposer-main/InternLM-XComposer-main/examples/web_demo.py", line 444, in generate_article
    self.selected = self.model_select_image(output_text, caps,
  File "/data/liwx/InternLM-XComposer-main/InternLM-XComposer-main/examples/web_demo.py", line 299, in model_select_image
    pre_img.append(images[len(pre_img) + ans2idx[answer]].cpu())
KeyError: '<'

**Comment by walkskysu** [comment]
我的跑不出来，只能把 model select image选项关掉

**Comment by WeiXuanLi-1024** [comment]
目前错误定位到 ans2idx 这个字典中没有 “<” ，暂时使用answer ="B" ,可以自动插图，但是Insert fixed button 还是会报错，期待官方一并修改

**Comment by myownskyW7** [comment]
感谢报告这个问题，我们会很快检查和修复这个bug。

Thank you for reporting this bug. We will check and fix it very soon.

**Comment by panzhang0212** [comment]
The bug has been fixes. Please pull the latest code.
