### ISSUE TITLE
webui运行internlm-xcomposer2-4khd-7b时报错

### ISSUE THREAD

**Issue by blackblue9** [InternLM/InternLM-XComposer#286]
我在通过python examples/gradio_demo_chat.py  --code_path=/mnt/tenant-home_speed/model/internlm-xcomposer2-4khd-7b/  --port 7804  运行internlm-xcomposer2-4khd-7b模型的时候出现以下报错，请问改如何解决呢？

`
Loading checkpoint shards: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 2/2 [14:18<00:00, 429.19s/it]
Some weights of InternLMXComposer2ForCausalLM were not initialized from the model checkpoint at /mnt/tenant-home_speed/model/internlm-xcomposer2-4khd-7b/ and are newly initialized: ['vit.vision_tower.vision_model.post_layernorm.weight', 'vit.vision_tower.vision_model.post_layernorm.bias', 'vit.vision_tower.vision_model.embeddings.position_ids']
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Running on local URL:  http://0.0.0.0:7804
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/site-packages/gradio/utils.py", line 650, in wrapper
    response = f(*args, **kwargs)
  File "/mnt/tenant-home_speed/qxj/MLLM/InternLM-XComposer-main/examples/gradio_demo_chat.py", line 254, in load_demo
    gr.Row(visible=True), gr.Accordion(visible=True))
TypeError: Accordion.__init__() missing 1 required positional argument: 'label'
Traceback (most recent call last):
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/site-packages/gradio/queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/site-packages/gradio/route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/site-packages/gradio/blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/site-packages/gradio/blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/site-packages/anyio/to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/site-packages/gradio/utils.py", line 650, in wrapper
    response = f(*args, **kwargs)
  File "/mnt/tenant-home_speed/qxj/MLLM/InternLM-XComposer-main/examples/gradio_demo_chat.py", line 212, in uploadimgs
    shutil.copy(image_path, self.folder)
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/shutil.py", line 416, in copy
    dst = os.path.join(dst, os.path.basename(src))
  File "/usr/local/miniconda3/envs/minicpm/lib/python3.10/posixpath.py", line 142, in basename
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not _TemporaryFileWrapper

`

**Comment by WeiminLee** [comment]
我也遇到了相同的问题，请问你有解决么？
gr.Row(visible=True), gr.Accordion(visible=True))
**TypeError: Accordion.__init__() missing 1 required positional argument: 'label'**
Traceback (most recent call last):

**Comment by blackblue9** [comment]
更新gradio版本到最新版本可以解决这个问题，但是又会报新的错误hh

**Comment by WeiminLee** [comment]
确实如此，刚升级到4.28.0  ，又报错了。

ception in thread Thread-4 (_do_normal_analytics_request):
Traceback (most recent call last):
  File "/home/workspace/lwm/lwm-ven/lib/python3.10/site-packages/httpx/_transports/default.py", line 69, in map_httpcore_exceptions
    yield
  File "/home/workspace/lwm/lwm-ven/lib/python3.10/site-packages/httpx/_transports/default.py", line 233, in handle_request
    resp = self._pool.handle_request(req)
  File "/home/workspace/lwm/lwm-ven/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 216, in handle_request
    raise exc from None
  File "/home/workspace/lwm/lwm-ven/lib/python3.10/site-packages/httpcore/_sync/connection_pool.py", line 196, in handle_request
    response = connection.handle_request(
  File "/home/workspace/lwm/lwm-ven/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 99, in handle_request
    raise exc
  File "/home/workspace/lwm/lwm-ven/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 76, in handle_request
    stream = self._connect(request)
  File "/home/workspace/lwm/lwm-ven/lib/python3.10/site-packages/httpcore/_sync/connection.py", line 122, in _connect
    stream = self._network_backend.connect_tcp(**kwargs)
  File "/home/workspace/lwm/lwm-ven/lib/python3.10/site-packages/httpcore/_backends/sync.py", line 205, in connect_tcp
    with map_exceptions(exc_map):
  File "/usr/local/python3/lib/python3.10/contextlib.py", line 153, in __exit__
    self.gen.throw(typ, value, traceback)
  File "/home/workspace/lwm/lwm-ven/lib/python3.10/site-packages/httpcore/_exceptions.py", line 14, in map_exceptions
    raise to_exc(exc) from exc
httpcore.ConnectTimeout: timed out
