### ISSUE TITLE
Error: click "Insert a fixed number of Images" button error

### ISSUE THREAD

**Issue by walkskysu** [InternLM/InternLM-XComposer#29]
Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Python\Python310\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Python\Python310\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "C:\Python\Python310\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Python\Python310\lib\site-packages\gradio\utils.py", line 650, in wrapper
    response = f(*args, **kwargs)
  File "E:\ai\InternLM-XComposer\examples\web_demo.py", line 468, in adjust_img
    caps = self.generate_loc_cap(idx_text_sections, int(img_num), progress)
  File "E:\ai\InternLM-XComposer\examples\web_demo.py", line 177, in generate_loc_cap
    inject_text, locs = self.generate_loc(text_sections, image_num,
  File "E:\ai\InternLM-XComposer\examples\web_demo.py", line 132, in generate_loc
    for _ in progress.tqdm([1], desc="image spotting"):
TypeError: Progress.tqdm() missing 1 required positional argument: 'iterable'
Traceback (most recent call last):
  File "C:\Python\Python310\lib\site-packages\gradio\queueing.py", line 388, in call_prediction
    output = await route_utils.call_process_api(
  File "C:\Python\Python310\lib\site-packages\gradio\route_utils.py", line 219, in call_process_api
    output = await app.get_blocks().process_api(
  File "C:\Python\Python310\lib\site-packages\gradio\blocks.py", line 1437, in process_api
    result = await self.call_function(
  File "C:\Python\Python310\lib\site-packages\gradio\blocks.py", line 1109, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "C:\Python\Python310\lib\site-packages\anyio\to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "C:\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "C:\Python\Python310\lib\site-packages\anyio\_backends\_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "C:\Python\Python310\lib\site-packages\gradio\utils.py", line 650, in wrapper
    response = f(*args, **kwargs)
  File "E:\ai\InternLM-XComposer\examples\web_demo.py", line 468, in adjust_img
    caps = self.generate_loc_cap(idx_text_sections, int(img_num), progress)
  File "E:\ai\InternLM-XComposer\examples\web_demo.py", line 177, in generate_loc_cap
    inject_text, locs = self.generate_loc(text_sections, image_num,
  File "E:\ai\InternLM-XComposer\examples\web_demo.py", line 132, in generate_loc
    for _ in progress.tqdm([1], desc="image spotting"):
TypeError: Progress.tqdm() missing 1 required positional argument: 'iterable'

**Comment by panzhang0212** [comment]
The bug has been fixes. Please pull the latest code.
