### ISSUE TITLE
运行web_demo.py，无法初始化模型

### ISSUE THREAD

**Issue by XingchenMengxiang** [InternLM/InternLM-XComposer#31]
Traceback (most recent call last):
  File "/home/batch/projects/InternLM-XComposer/examples/web_demo.py", line 816, in <module>
    demo_ui = Demo_UI()
  File "/home/batch/projects/InternLM-XComposer/examples/web_demo.py", line 47, in __init__
    self.llm_model = AutoModel.from_pretrained(
  File "/home/batch/rt/InternLM-X/lib/python3.10/site-packages/transformers/models/auto/auto_factory.py", line 479, in from_pretrained
    return model_class.from_pretrained(
  File "/home/batch/rt/InternLM-X/lib/python3.10/site-packages/transformers/modeling_utils.py", line 2675, in from_pretrained
    model = cls(config, *model_args, **model_kwargs)
  File "/home/batch/.cache/huggingface/modules/transformers_modules/internlm-xcomposer-vl-7b/modeling_InternLM_XComposer.py", line 49, in __init__
    self.Qformer, self.query_tokens = self.init_qformer(
  File "/home/batch/.cache/huggingface/modules/transformers_modules/internlm-xcomposer-vl-7b/modeling_InternLM_XComposer.py", line 122, in init_qformer
    encoder_config = BertConfig.from_pretrained("bert-base-uncased")
  File "/home/batch/rt/InternLM-X/lib/python3.10/site-packages/transformers/configuration_utils.py", line 547, in from_pretrained
    config_dict, kwargs = cls.get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/batch/rt/InternLM-X/lib/python3.10/site-packages/transformers/configuration_utils.py", line 574, in get_config_dict
    config_dict, kwargs = cls._get_config_dict(pretrained_model_name_or_path, **kwargs)
  File "/home/batch/rt/InternLM-X/lib/python3.10/site-packages/transformers/configuration_utils.py", line 629, in _get_config_dict
    resolved_config_file = cached_file(
  File "/home/batch/rt/InternLM-X/lib/python3.10/site-packages/transformers/utils/hub.py", line 452, in cached_file
    raise EnvironmentError(
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like bert-base-uncased is not the path to a directory containing a file named config.json.
Checkout your internet connection or see how to run the library in offline mode at 'https://huggingface.co/docs/transformers/installation#offline-mode'.

**Comment by 2132660698** [comment]
应该是[huggingface.co](https://huggingface.co/)'对国内墙了，需要下载模型到本地，然后在代码里面修改模型路径。

**Comment by XingchenMengxiang** [comment]
> 应该是[huggingface.co](https://huggingface.co/)'对国内墙了，需要下载模型到本地，然后在代码里面修改模型路径。
已经本地地址了 

 self.llm_model = AutoModel.from_pretrained(
               '/home/batch/data/internlm-xcomposer-vl-7b', local_files_only=True ,trust_remote_code=True)
           tokenizer = AutoTokenizer.from_pretrained(
               '/home/batch/data/internlm-xcomposer-vl-7b', local_files_only=True ,trust_remote_code=True)


是不是哪里还需改 ？

**Comment by 2132660698** [comment]
bert-base-uncased从[huggingface.co](https://huggingface.co/)下载后修改
huggingface\internlm-xcomposer\modeling_InternLM_XComposer.py

**Comment by myownskyW7** [comment]
感谢报告这个问题，我们会很快检查和修复这个bug。

Thank you for reporting this bug. We will check and fix it very soon.

**Comment by myownskyW7** [comment]
这个问题我们已经在Hugging Face的代码里面修复了，麻烦重新下载最新的代码试一下。如果有其他问题还请反馈，谢谢

The issue regarding Hugging Face access has been resolved. Please pull the latest version of the code on Hugging Face. If necessary, feel free to reopen this issue.

**Comment by sssssshf** [comment]
> 这个问题我们已经在Hugging Face的代码里面修复了，麻烦重新下载最新的代码试一下。如果有其他问题还请反馈，谢谢
> 
> The issue regarding Hugging Face access has been resolved. Please pull the latest version of the code on Hugging Face. If necessary, feel free to reopen this issue.

我把模型下载到本地了 用的最新的代码还是会出现这个问题
