### ISSUE TITLE
Why submit the codes with obvious bugs 

### ISSUE THREAD

**Issue by LinaZhangCoding** [InternLM/InternLM-XComposer#346]
for example_code/example_chat.py,   from examples.utils import auto_configure_device_map  "There is no such file"
after modify from utils import auto_configure_device_map , it shows 

.cache/huggingface/modules/transformers_modules/internlm/internlm-xcomposer2d5-7b/eb12cdf26df23c26b0f485bbb8c674d7ceb3a02e/modeling_internlm_xcomposer2.py", line 259, in interleav_wrap_chat
    part_tokens = self.tokenizer(
TypeError: 'NoneType' object is not callable

But the tokenizer file exist and print(tokenizer) it is not null.

**Comment by LightDXY** [comment]
bug fixed

**Comment by yusirhhh** [comment]
Traceback (most recent call last):
  File "/mnt/data/mmyu/eqa/explore-eqa/others/test_diff_vlm/InternLM_XComposer.py", line 18, in <module>                                                                                                              response, _ = model.chat(tokenizer, query, image, do_sample=False, num_beams=3, use_meta=True)
  File "/home/mmyu/anaconda3/envs/eval_cog/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
  File "/home/mmyu/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2d5-7b/modeling_internlm_xcomposer2.py", line 594, in chat
    inputs, im_mask, _ = self.interleav_wrap_chat(query, image, history=history, meta_instruction=meta_instruction, hd_num=hd_num)
  File "/home/mmyu/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2d5-7b/modeling_internlm_xcomposer2.py", line 259, in interleav_wrap_chat
    part_tokens = self.tokenizer(
TypeError: 'NoneType' object is not callable

**Comment by hj611** [comment]
> 错误修复

Why do I still have this problem？

**Comment by Upcreat** [comment]
我也有相同的问题出现
