### ISSUE TITLE
RuntimeError: CUDA error: invalid device ordinal

### ISSUE THREAD

**Issue by L0CUST** [InternLM/InternLM-XComposer#361]
I followed all the steps in the fine-tuning script, but an error occurs.( used xcomposer-4khd model) 
```python
RuntimeError: CUDA error: invalid device ordinal
CUDA kernel errors might be asynchronously reported at some other API call, so the stacktrace below might be incorrect.
For debugging consider passing CUDA_LAUNCH_BLOCKING=1.
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
``` 

So I added a few codes to finetune.py , but I keep getting errors
```python
import os
os.environ['CUDA_LAUNCH_BLOCKING'] = '1'
os.environ["CUDA_VISIBLE_DEVICES"] = "0"
os.environ["TORCH_USE_CUDA_DSA"] = '1'

RuntimeError: CUDA error: invalid device ordinal
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.
``` 

This is because of the lack of VRAM? I use two A5000 now.
How much VRAM do I need on finetuning? (full or LoRa)

**Comment by yuhangzang** [comment]
Can u check ur pytorch version? We test `torch==2.0.1` in our environment.

**Comment by L0CUST** [comment]
pytorch is 2.0.1+cu117

**Comment by L0CUST** [comment]
```
WARNING:torch.distributed.run:
*****************************************
Setting OMP_NUM_THREADS environment variable for each process to be 1 in default, to avoid your system being overloaded, please further tune the variable for optimal performance in your application as needed. 
*****************************************
[2024-07-09 16:43:49,060] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-07-09 16:43:49,060] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-07-09 16:43:49,061] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-07-09 16:43:49,062] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-07-09 16:43:49,063] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-07-09 16:43:49,065] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-07-09 16:43:49,065] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
[2024-07-09 16:43:49,090] [INFO] [real_accelerator.py:203:get_accelerator] Setting ds_accelerator to cuda (auto detect)
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  Please specify the CUTLASS repo directory as environment variable $CUTLASS_PATH
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  sparse_attn requires a torch version >= 1.5 and < 2.0 but detected 2.0
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
 [WARNING]  using untested triton version (2.0.0), only 1.0.0 is known to be compatible
/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-07-09 16:43:50,285] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-07-09 16:43:50,285] [INFO] [comm.py:668:init_distributed] Initializing TorchBackend in DeepSpeed with backend nccl
[2024-07-09 16:43:50,291] [INFO] [comm.py:637:init_distributed] cdb=None
/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-07-09 16:43:50,298] [INFO] [comm.py:637:init_distributed] cdb=None
/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-07-09 16:43:50,307] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-07-09 16:43:50,307] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-07-09 16:43:50,307] [INFO] [comm.py:637:init_distributed] cdb=None
/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/deepspeed.py:23: FutureWarning: transformers.deepspeed module is deprecated and will be removed in a future version. Please import deepspeed modules directly from transformers.integrations
  warnings.warn(
[2024-07-09 16:43:50,317] [INFO] [comm.py:637:init_distributed] cdb=None
[2024-07-09 16:43:50,322] [INFO] [comm.py:637:init_distributed] cdb=None
Traceback (most recent call last):
  File "/home/user/Desktop/internlm/InternLM-XComposer/InternLM-XComposer-2.0/finetune/finetune.py", line 319, in <module>
    train()
  File "/home/user/Desktop/internlm/InternLM-XComposer/InternLM-XComposer-2.0/finetune/finetune.py", line 230, in train
    ) = parser.parse_args_into_dataclasses()
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 119, in __init__
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1405, in __post_init__
    and (self.device.type != "cuda")
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1852, in device
    return self._setup_devices
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1788, in _setup_devices
    self.distributed_state = PartialState(timeout=timedelta(seconds=self.ddp_timeout))
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/accelerate/state.py", line 280, in __init__
    self.set_device()
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/accelerate/state.py", line 790, in set_device
    torch.cuda.set_device(self.device)
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/home/user/Desktop/internlm/InternLM-XComposer/InternLM-XComposer-2.0/finetune/finetune.py", line 319, in <module>
    train()
  File "/home/user/Desktop/internlm/InternLM-XComposer/InternLM-XComposer-2.0/finetune/finetune.py", line 230, in train
    ) = parser.parse_args_into_dataclasses()
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses
Traceback (most recent call last):
    obj = dtype(**inputs)
  File "/home/user/Desktop/internlm/InternLM-XComposer/InternLM-XComposer-2.0/finetune/finetune.py", line 319, in <module>
  File "<string>", line 119, in __init__
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1405, in __post_init__
    train()
  File "/home/user/Desktop/internlm/InternLM-XComposer/InternLM-XComposer-2.0/finetune/finetune.py", line 230, in train
    ) = parser.parse_args_into_dataclasses()
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses
Traceback (most recent call last):
  File "/home/user/Desktop/internlm/InternLM-XComposer/InternLM-XComposer-2.0/finetune/finetune.py", line 319, in <module>
    obj = dtype(**inputs)
  File "<string>", line 119, in __init__
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1405, in __post_init__
    and (self.device.type != "cuda")
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1852, in device
    train()
  File "/home/user/Desktop/internlm/InternLM-XComposer/InternLM-XComposer-2.0/finetune/finetune.py", line 230, in train
    ) = parser.parse_args_into_dataclasses()
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 119, in __init__
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1405, in __post_init__
    and (self.device.type != "cuda")
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1852, in device
    return self._setup_devices
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1788, in _setup_devices
    and (self.device.type != "cuda")
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1852, in device
    return self._setup_devices
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1788, in _setup_devices
    self.distributed_state = PartialState(timeout=timedelta(seconds=self.ddp_timeout))
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/accelerate/state.py", line 280, in __init__
    self.set_device()
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/accelerate/state.py", line 790, in set_device
    return self._setup_devices
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1788, in _setup_devices
    torch.cuda.set_device(self.device)
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/torch/cuda/__init__.py", line 350, in set_device
    self.distributed_state = PartialState(timeout=timedelta(seconds=self.ddp_timeout))
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/accelerate/state.py", line 280, in __init__
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    self.set_device()
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/accelerate/state.py", line 790, in set_device
    torch.cuda.set_device(self.device)
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    self.distributed_state = PartialState(timeout=timedelta(seconds=self.ddp_timeout))
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/accelerate/state.py", line 280, in __init__
    self.set_device()
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/accelerate/state.py", line 790, in set_device
Traceback (most recent call last):
  File "/home/user/Desktop/internlm/InternLM-XComposer/InternLM-XComposer-2.0/finetune/finetune.py", line 319, in <module>
    torch.cuda.set_device(self.device)
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

    train()
  File "/home/user/Desktop/internlm/InternLM-XComposer/InternLM-XComposer-2.0/finetune/finetune.py", line 230, in train
    ) = parser.parse_args_into_dataclasses()
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 119, in __init__
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1405, in __post_init__
    and (self.device.type != "cuda")
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1852, in device
    return self._setup_devices
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1788, in _setup_devices
    self.distributed_state = PartialState(timeout=timedelta(seconds=self.ddp_timeout))
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/accelerate/state.py", line 280, in __init__
    self.set_device()
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/accelerate/state.py", line 790, in set_device
    torch.cuda.set_device(self.device)
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

Traceback (most recent call last):
  File "/home/user/Desktop/internlm/InternLM-XComposer/InternLM-XComposer-2.0/finetune/finetune.py", line 319, in <module>
    train()
  File "/home/user/Desktop/internlm/InternLM-XComposer/InternLM-XComposer-2.0/finetune/finetune.py", line 230, in train
    ) = parser.parse_args_into_dataclasses()
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/hf_argparser.py", line 338, in parse_args_into_dataclasses
    obj = dtype(**inputs)
  File "<string>", line 119, in __init__
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1405, in __post_init__
    and (self.device.type != "cuda")
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1852, in device
    return self._setup_devices
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/utils/generic.py", line 54, in __get__
    cached = self.fget(obj)
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/transformers/training_args.py", line 1788, in _setup_devices
    self.distributed_state = PartialState(timeout=timedelta(seconds=self.ddp_timeout))
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/accelerate/state.py", line 280, in __init__
    self.set_device()
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/accelerate/state.py", line 790, in set_device
    torch.cuda.set_device(self.device)
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/torch/cuda/__init__.py", line 350, in set_device
    torch._C._cuda_setDevice(device)
RuntimeError: CUDA error: invalid device ordinal
Compile with `TORCH_USE_CUDA_DSA` to enable device-side assertions.

/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/huggingface_hub/file_download.py:1132: FutureWarning: `resume_download` is deprecated and will be removed in version 1.0.0. Downloads always resume when possible. If you want to force a new download, use `force_download=True`.
  warnings.warn(
You are using a model of type internlmxcomposer2 to instantiate a model of type internlm2. This is not supported for all configurations of models and can yield errors.
Load model from: internlm/internlm-xcomposer2-4khd-7b
You are using a model of type internlmxcomposer2 to instantiate a model of type internlm2. This is not supported for all configurations of models and can yield errors.
Load model from: internlm/internlm-xcomposer2-4khd-7b
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 6351 closing signal SIGTERM
WARNING:torch.distributed.elastic.multiprocessing.api:Sending process 6352 closing signal SIGTERM
ERROR:torch.distributed.elastic.multiprocessing.api:failed (exitcode: 1) local_rank: 2 (pid: 6353) of binary: /home/user/anaconda3/envs/intern/bin/python
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/intern/bin/torchrun", line 8, in <module>
    sys.exit(main())
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 346, in wrapper
    return f(*args, **kwargs)
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/torch/distributed/run.py", line 794, in main
    run(args)
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/torch/distributed/run.py", line 785, in run
    elastic_launch(
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 134, in __call__
    return launch_agent(self._config, self._entrypoint, list(args))
  File "/home/user/anaconda3/envs/intern/lib/python3.9/site-packages/torch/distributed/launcher/api.py", line 250, in launch_agent
    raise ChildFailedError(
torch.distributed.elastic.multiprocessing.errors.ChildFailedError: 
============================================================
finetune.py FAILED
------------------------------------------------------------
Failures:
[1]:
  time      : 2024-07-09_16:43:53
  host      : AI-PC
  rank      : 3 (local_rank: 3)
  exitcode  : 1 (pid: 6354)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[2]:
  time      : 2024-07-09_16:43:53
  host      : AI-PC
  rank      : 4 (local_rank: 4)
  exitcode  : 1 (pid: 6355)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[3]:
  time      : 2024-07-09_16:43:53
  host      : AI-PC
  rank      : 5 (local_rank: 5)
  exitcode  : 1 (pid: 6356)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[4]:
  time      : 2024-07-09_16:43:53
  host      : AI-PC
  rank      : 6 (local_rank: 6)
  exitcode  : 1 (pid: 6357)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
[5]:
  time      : 2024-07-09_16:43:53
  host      : AI-PC
  rank      : 7 (local_rank: 7)
  exitcode  : 1 (pid: 6358)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
------------------------------------------------------------
Root Cause (first observed failure):
[0]:
  time      : 2024-07-09_16:43:53
  host      : AI-PC
  rank      : 2 (local_rank: 2)
  exitcode  : 1 (pid: 6353)
  error_file: <N/A>
  traceback : To enable traceback see: https://pytorch.org/docs/stable/elastic/errors.html
============================================================

```

**Comment by yuhangzang** [comment]
Can u downgrade the torch version == 1.13 and re-try? Thx.
