### ISSUE TITLE
Can't run with multiple gpu

### ISSUE THREAD

**Issue by volcverse** [InternLM/InternLM-XComposer#364]
Hello, thanks for the great work!

I refer to the `example_code/example_chat.py` to run the newest InternLM-XComposer-2.5 model using 4 NVIDIA 4090 GPUs. But still meet the OOM problem. It seems that although the weights are divided successfully, the first gpu always runs into OOM when `model.chat` is called.

Any response will be greatly appreciated!

**Comment by Uoops** [comment]
same

**Comment by hyyuan123** [comment]
I refer to the example_code/example_chat.py to run the newest InternLM-XComposer-2.5 model using 4 A800 GPUs. But still meet the OOM problem.

**Comment by waltonfuture** [comment]
same question

**Comment by yhcao6** [comment]
Please try to install transformers==4.33.1 with the following command and try again:
```bash
pip install transformers==4.33.1
```

**Comment by YerongLi** [comment]
I used transformers==4.36.0 and met the following issue

`
You should probably TRAIN this model on a down-stream task to be able to use it for predictions and inference.
Traceback (most recent call last):
  File "/home/yerong2/representation-engineering/examples/example_chat.py", line 112, in <module>
    response, _ = model.chat(tokenizer, query, image, do_sample=False, num_beams=3, use_meta=True)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yerong2/local/miniconda3/envs/mllm/lib/python3.11/site-packages/torch/utils/_contextlib.py", line 115, in decorate_context
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/yerong2/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-vl-7b/modeling_internlm_xcomposer2.py", line 500, in chat
    image = self.encode_img(image)
            ^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yerong2/.cache/huggingface/modules/transformers_modules/internlm-xcomposer2-vl-7b/modeling_internlm_xcomposer2.py", line 116, in encode_img
    assert isinstance(image, torch.Tensor)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

`

**Comment by YerongLi** [comment]
> Hello, thanks for the great work!
> 
> I refer to the `example_code/example_chat.py` to run the newest InternLM-XComposer-2.5 model using 4 NVIDIA 4090 GPUs. But still meet the OOM problem. It seems that although the weights are divided successfully, the first gpu always runs into OOM when `model.chat` is called.
> 
> Any response will be greatly appreciated!

I found the model cannot take multiple images as inputs, neither can it take a list of images thus the fix is 

- Change the image input to a singleton: https://github.com/InternLM/InternLM-XComposer/blob/99a56be441c05337eeed5aacbcb88da447ae2d49/example_code/example_chat.py#L33C1-L33C33 
```
image = './examples/dubai.png'
```
- Add <ImageHere> Flag https://github.com/InternLM/InternLM-XComposer/blob/99a56be441c05337eeed5aacbcb88da447ae2d49/example_code/example_chat.py#L32
```
query = '<ImageHere>Please describe this image'
```

**Comment by resi1ience** [comment]
> Please try to install transformers==4.33.1 with the following command and try again:
> 
> ```shell
> pip install transformers==4.33.1
> ```

Still meet the same problem with transformers 4.33.1. I'm running the video understanding example on the huggingface.
Response will be greatly appreciated

**Comment by gyniy** [comment]
But still meet the OOM problem with transformers 4.33.1,
