### ISSUE TITLE
size mismatch for vit.vision_tower.vision_model.embeddings.position_embedding.weight

### ISSUE THREAD

**Issue by cool-xuan** [InternLM/InternLM-XComposer#395]
When I try to inference [internlm-xcomposer2d5-7b](https://huggingface.co/internlm/internlm-xcomposer2d5-7b), I find the bug of size mismatch.

bug details:
```
Traceback (most recent call last):
  File "/workspace/mllm/InternLM-XComposer/multi_image_chat.py", line 7, in <module>
    model = AutoModel.from_pretrained('./ckpt/internlm-xcomposer2d5-7b', torch_dtype=torch.bfloat16, trust_remote_code=True).cuda().eval().half()
  File "/opt/conda/envs/intern_clean/lib/python3.9/site-packages/transformers/models/auto/auto_factory.py", line 558, in from_pretrained
    return model_class.from_pretrained(
  File "/opt/conda/envs/intern_clean/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3187, in from_pretrained
    ) = cls._load_pretrained_model(
  File "/opt/conda/envs/intern_clean/lib/python3.9/site-packages/transformers/modeling_utils.py", line 3636, in _load_pretrained_model
    raise RuntimeError(f"Error(s) in loading state_dict for {model.__class__.__name__}:\n\t{error_msg}")
RuntimeError: Error(s) in loading state_dict for InternLMXComposer2ForCausalLM:
        size mismatch for vit.vision_tower.vision_model.embeddings.position_embedding.weight: copying a param with shape torch.Size([1601, 1024]) from checkpoint, the shape in current model is torch.Size([577, 1024]).
        You may consider adding `ignore_mismatched_sizes=True` in the model `from_pretrained` method.
```
Please note that I have changed the the vision_tower link from 
```
def build_vision_tower():
    vision_tower = 'internlm/internlm-xcomposer2d5-clip'
    return CLIPVisionTower(vision_tower)
```
```
def build_vision_tower():
    vision_tower = './ckpt/clip-vit-large-patch14-336'
    return CLIPVisionTower(vision_tower)
```
If this modification leads to this bug?

**Comment by LightDXY** [comment]
of course it leads to the problem, the clip-336 means the input resolution is 336 and leads to 576 image tokens. While the input resolution of internlm-xcomposer2d5-clip is 560 and leads to 1600 image tokens.
