### ISSUE TITLE
inference multi-image input using the 4-bit model

### ISSUE THREAD

**Issue by vietpho** [InternLM/InternLM-XComposer#405]
Hi,
I didn't receive a response, so I'm posting my question again. Once I get a reply, I'll delete my previous post.

My GPU memory is only 24GB, so I want to use the 4-bit model. 
I have read your instructions and tried to run inference with multi-image input using the 4-bit model based on the following two code blocks, but I encountered an error. 
(I have downloaded all the checkpoints and necessary files locally and both images and model checkpoints load correctly.)

Could you please provide  an example inference code that works with multi-image input using the 4-bit model? 
Also, is it possible to use multi-turn dialog with the 4-bit model?

Here are the two code blocks I referenced:
```
from lmdeploy import TurbomindEngineConfig, pipeline
from lmdeploy.vl import load_image
engine_config = TurbomindEngineConfig(model_format='awq')
pipe = pipeline('internlm/internlm-xcomposer2d5-7b-4bit', backend_config=engine_config)
image = load_image('examples/dubai.png')
response = pipe(('describe this image', image))
print(response.text)
```

```
from lmdeploy import pipeline, GenerationConfig
from lmdeploy.vl.constants import IMAGE_TOKEN
from lmdeploy.vl import load_image

query = f'Image1 {IMAGE_TOKEN}; Image2 {IMAGE_TOKEN}; Image3 {IMAGE_TOKEN}; I want to buy a car from the three given cars, analyze their advantages and weaknesses one by one'

urls = [
    'https://raw.githubusercontent.com/InternLM/InternLM-XComposer/main/examples/cars1.jpg',
    'https://raw.githubusercontent.com/InternLM/InternLM-XComposer/main/examples/cars2.jpg',
    'https://raw.githubusercontent.com/InternLM/InternLM-XComposer/main/examples/cars3.jpg'
]
images = [load_image(url) for url in urls]

pipe = pipeline('internlm/internlm-xcomposer2d5-7b', log_level='INFO')
output = pipe((query, images), gen_config=GenerationConfig(top_k=0, top_p=0.8, random_seed=89247526689433939))
```

Here is the code I wrote based on the above two code blocks:

```
from lmdeploy import TurbomindEngineConfig, pipeline, GenerationConfig
from lmdeploy.vl import load_image
from lmdeploy.vl.constants import IMAGE_TOKEN
import os

os.chdir(os.path.dirname(os.path.abspath(__file__)))

model_path = '/workspace/InternLM-XComposer/xcomp_4bit_files'

engine_config = TurbomindEngineConfig(model_format='awq')
pipe = pipeline(model_path, backend_config=engine_config)

img_paths = [
    './examples/cars1.jpg',
    './examples/cars2.jpg',
    './examples/cars3.jpg'
]

images = [load_image(img_path) for img_path in img_paths]

query = f'Image1 {IMAGE_TOKEN}; Image2 {IMAGE_TOKEN}; Image3 {IMAGE_TOKEN}; I want to buy a car from the three given cars, analyze their advantages and weaknesses one by one'

output = pipe((query, images), gen_config=GenerationConfig(top_k=0, top_p=0.8, random_seed=89247526689433939))

print(output.text)

```

Here is the error I get when running the above code:

```
Traceback (most recent call last):
  File "/workspace/InternLM-XComposer/test_lmdeploy.py", line 42, in <module>
    output = pipe((query, images), gen_config=GenerationConfig(top_k=0, top_p=0.8, random_seed=89247526689433939))
  File "/usr/local/venv/lib/python3.9/site-packages/lmdeploy/serve/vl_async_engine.py", line 123, in __call__
    return super().__call__(prompts, **kwargs)
  File "/usr/local/venv/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 304, in __call__
    return self.batch_infer(prompts,
  File "/usr/local/venv/lib/python3.9/site-packages/lmdeploy/serve/vl_async_engine.py", line 109, in batch_infer
    return super().batch_infer(prompts, **kwargs)
  File "/usr/local/venv/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 428, in batch_infer
    _get_event_loop().run_until_complete(gather())
  File "/usr/lib/python3.9/asyncio/base_events.py", line 642, in run_until_complete
    return future.result()
  File "/usr/local/venv/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 425, in gather
    await asyncio.gather(
  File "/usr/local/venv/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 410, in _inner_call
    async for out in generator:
  File "/usr/local/venv/lib/python3.9/site-packages/lmdeploy/serve/async_engine.py", line 571, in generate
    prompt_input = await self._get_prompt_input(prompt,
  File "/usr/local/venv/lib/python3.9/site-packages/lmdeploy/serve/vl_async_engine.py", line 59, in _get_prompt_input
    segs = decorated.split(IMAGE_TOKEN)
AttributeError: 'NoneType' object has no attribute 'split'
```

Thank you for your help!

**Comment by yhcao6** [comment]
Hi, I can run your code, may I ask if you can run [example_code/4bit/lmdeploy_chat.py](https://github.com/InternLM/InternLM-XComposer/blob/main/example_code/4bit/lmdeploy_chat.py) and [example_code/4bit/lmdeploy_chat_4bit.py](https://github.com/InternLM/InternLM-XComposer/blob/main/example_code/4bit/lmdeploy_chat_4bit.py).

**Comment by vietpho** [comment]
I am unable to run even the example codes. The same error occurs every time. I would really like to run these, but it seems impossible. Is there any way to resolve this issue?

```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[1], line 18
     16 pipe = pipeline(model_path, backend_config=engine_config)
     17 image = load_image('dubai.png')
---> 18 response = pipe(('describe this image', image))
     19 print(response.text)
     21 info = nvidia_smi.nvmlDeviceGetMemoryInfo(handle)

File ~/miniconda3/envs/xcomp/lib/python3.9/site-packages/proj/serve/vl_async_engine.py:123, in VLAsyncEngine.__call__(self, prompts, **kwargs)
    121 """Inference a batch of prompts."""
    122 prompts = self._convert_prompts(prompts)
--> 123 return super().__call__(prompts, **kwargs)

File ~/miniconda3/envs/xcomp/lib/python3.9/site-packages/proj/serve/async_engine.py:305, in AsyncEngine.__call__(self, prompts, gen_config, request_output_len, top_k, top_p, temperature, repetition_penalty, ignore_eos, do_preprocess, adapter_name, use_tqdm, **kwargs)
    297 if gen_config is None:
    298     gen_config = GenerationConfig(
    299         max_new_tokens=request_output_len,
    300         top_k=top_k,
   (...)
    303         repetition_penalty=repetition_penalty,
    304         ignore_eos=ignore_eos)
--> 305 return self.batch_infer(prompts,
    306                         gen_config=gen_config,
    307                         do_preprocess=do_preprocess,
    308                         adapter_name=adapter_name,
    309                         use_tqdm=use_tqdm,
    310                         **kwargs)

File ~/miniconda3/envs/xcomp/lib/python3.9/site-packages/proj/serve/vl_async_engine.py:109, in VLAsyncEngine.batch_infer(self, prompts, **kwargs)
    107 """Inference a batch of prompts."""
    108 prompts = self._convert_prompts(prompts)
--> 109 return super().batch_infer(prompts, **kwargs)

File ~/miniconda3/envs/xcomp/lib/python3.9/site-packages/proj/serve/async_engine.py:429, in AsyncEngine.batch_infer(self, prompts, gen_config, do_preprocess, adapter_name, use_tqdm, **kwargs)
    425 async def gather():
    426     await asyncio.gather(
    427         *[_inner_call(i, generators[i]) for i in range(len(prompts))])
--> 429 _get_event_loop().run_until_complete(gather())
    430 outputs = outputs[0] if need_list_wrap else outputs
    431 return outputs

File ~/miniconda3/envs/xcomp/lib/python3.9/site-packages/nest_asyncio.py:98, in _patch_loop.<locals>.run_until_complete(self, future)
     95 if not f.done():
     96     raise RuntimeError(
     97         'Event loop stopped before Future completed.')
---> 98 return f.result()

File ~/miniconda3/envs/xcomp/lib/python3.9/asyncio/futures.py:201, in Future.result(self)
    199 self.__log_traceback = False
    200 if self._exception is not None:
--> 201     raise self._exception
    202 return self._result

File ~/miniconda3/envs/xcomp/lib/python3.9/asyncio/tasks.py:258, in Task.__step(***failed resolving arguments***)
    256         result = coro.send(None)
    257     else:
--> 258         result = coro.throw(exc)
    259 except StopIteration as exc:
    260     if self._must_cancel:
    261         # Task is cancelled right before coro stops.

File ~/miniconda3/envs/xcomp/lib/python3.9/site-packages/proj/serve/async_engine.py:426, in AsyncEngine.batch_infer.<locals>.gather()
    425 async def gather():
--> 426     await asyncio.gather(
    427         *[_inner_call(i, generators[i]) for i in range(len(prompts))])

File ~/miniconda3/envs/xcomp/lib/python3.9/asyncio/tasks.py:328, in Task.__wakeup(self, future)
    326 def __wakeup(self, future):
    327     try:
--> 328         future.result()
    329     except BaseException as exc:
    330         # This may also be a cancellation.
    331         self.__step(exc)

File ~/miniconda3/envs/xcomp/lib/python3.9/asyncio/tasks.py:256, in Task.__step(***failed resolving arguments***)
    252 try:
    253     if exc is None:
    254         # We use the `send` method directly, because coroutines
    255         # don't have `__iter__` and `__next__` methods.
--> 256         result = coro.send(None)
    257     else:
    258         result = coro.throw(exc)

File ~/miniconda3/envs/xcomp/lib/python3.9/site-packages/proj/serve/async_engine.py:411, in AsyncEngine.batch_infer.<locals>._inner_call(i, generator)
    410 async def _inner_call(i, generator):
--> 411     async for out in generator:
    412         outputs[i].text += out.response
    413         outputs[i].generate_token_len = out.generate_token_len

File ~/miniconda3/envs/xcomp/lib/python3.9/site-packages/proj/serve/async_engine.py:576, in AsyncEngine.generate(self, messages, session_id, gen_config, tools, stream_response, sequence_start, sequence_end, step, do_preprocess, adapter_name, **kwargs)
    573     gen_config.n = 1
    574 prompt = messages
--> 576 prompt_input = await self._get_prompt_input(prompt,
    577                                             do_preprocess,
    578                                             sequence_start,
    579                                             adapter_name,
    580                                             tools=tools)
    581 prompt = prompt_input['prompt']
    582 input_ids = prompt_input['input_ids']

File ~/miniconda3/envs/xcomp/lib/python3.9/site-packages/proj/serve/vl_async_engine.py:59, in VLAsyncEngine._get_prompt_input(self, prompt, do_preprocess, sequence_start, adapter_name, tools, **kwargs)
     57 else:
     58     decorated = prompt
---> 59 segs = decorated.split(IMAGE_TOKEN)
     61 results = {}
     62 input_ids = []

AttributeError: 'NoneType' object has no attribute 'split'

```

**Comment by yhcao6** [comment]
There might be an issue with LMDeploy. Ensure you install the correct version that matches your GPU and Python environment. You can download the appropriate version here: https://github.com/zhyncs/lmdeploy-build/releases.
