### ISSUE TITLE
TypeError: 'NoneType' object is not callable

### ISSUE THREAD

**Issue by hj611** [InternLM/InternLM-XComposer#413]
Traceback (most recent call last):
  File "InternLM-XComposer-main/test.py", line 52, in <module>
    response, _ = model.chat(tokenizer, query, image, do_sample=False, num_beams=3, use_meta=True)
  File "Anaconda/envs/intern_clean/lib/python3.9/site-packages/torch/utils/_contextlib.py", line 116, in decorate_context
    return func(*args, **kwargs)
  File "/cache/modules/transformers_modules/internlm/internlm-xcomposer2d5-7b/4aa81f2bbf20a9ddd4137dfe847c142adf07b652/modeling_internlm_xcomposer2.py", line 631, in chat
    inputs, im_mask, _ = self.interleav_wrap_chat(query, image, history=history, meta_instruction=meta_instruction, hd_num=hd_num)
  File "/cache/modules/transformers_modules/internlm/internlm-xcomposer2d5-7b/4aa81f2bbf20a9ddd4137dfe847c142adf07b652/modeling_internlm_xcomposer2.py", line 259, in interleav_wrap_chat
    part_tokens = self.tokenizer(
TypeError: 'NoneType' object is not callable

**Comment by LightDXY** [comment]
run the following code before the chat.
```
model.tokenizer = tokenizer
```

**Comment by MathewCrespo** [comment]
> run the following code before the chat.
> 
> ```
> model.tokenizer = tokenizer
> ```

I have run this code before the chat, but got the same problem.
