### ISSUE TITLE
训练lora部分报错

### ISSUE THREAD

**Issue by LiuXinyu12378** [InternLM/InternLM-XComposer#53]
我想做lora训练，只保冻结了其他部分，只保留了lora_A和lora_B,但是反向传播的时候会报错
    # 冻结visual_encoder, ln_vision 和 internlm_model 的参数
    for param in model.visual_encoder.parameters():
        param.requires_grad = False

    for param in model.ln_vision.parameters():
        param.requires_grad = False
    
    for param in model.Qformer.parameters():
        param.requires_grad = False

    for param in model.internlm_model.parameters():
        param.requires_grad = False

    # 解冻需要训练的lora_A和lora_B的参数
    for name, param in model.named_parameters():
        if "lora_A" in name or "lora_B" in name:
            param.requires_grad = True

训练代码：
        input_ids = data['input_ids'].to(device, dtype=torch.long)
        labels = data['labels'].to(device, dtype=torch.long)
        attention_mask= data['attention_mask'].to(device, dtype=torch.long)
        outputs = model.internlm_model(
            input_ids=input_ids,
            labels=labels,
            attention_mask=attention_mask
        )
        loss = outputs.loss
        # 反向传播，计算当前梯度
        loss.backward()
        
错误如下：
Traceback (most recent call last):
  File "/data/xinyuuliu/InternLM-XComposer/train_model/train.py", line 190, in <module>
    main()
  File "/data/xinyuuliu/InternLM-XComposer/train_model/train.py", line 175, in main
    train(epoch, model, device, training_loader, optimizer, gradient_accumulation_steps,model_output_dir)
  File "/data/xinyuuliu/InternLM-XComposer/train_model/train.py", line 55, in train
    loss.backward()
  File "/root/miniconda3/envs/internLM/lib/python3.9/site-packages/torch/_tensor.py", line 487, in backward
    torch.autograd.backward(
  File "/root/miniconda3/envs/internLM/lib/python3.9/site-packages/torch/autograd/__init__.py", line 200, in backward
    Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
  File "/root/miniconda3/envs/internLM/lib/python3.9/site-packages/torch/autograd/function.py", line 274, in apply
    return user_fn(self, *args)
  File "/root/.cache/huggingface/modules/transformers_modules/internlm-xcomposer-7b/modeling_InternLM.py", line 80, in backward
    rotary_emb.apply_rotary(dq1, dq2, rearrange(cos[:seqlen], 's d -> s 1 d'),
NameError: name 'rotary_emb' is not defined

**Comment by yhcao6** [comment]
训练过程中用到了flash attention和rotatry embedding，可以用下面的命令安装：
```base
# install flash attention
git clone git@github.com:Dao-AILab/flash-attention.git
cd flash-attention
python setup.py install

# install rotaty operator
cd csrc/rotary
pip install -e .
```

**Comment by LiuXinyu12378** [comment]
感谢！
