### ISSUE TITLE
ERROR: InternLMXComposerTokenizer' object has no attribute 'sp_model'

### ISSUE THREAD

**Issue by yaofeng** [InternLM/InternLM-XComposer#94]
I run the "examples/web_demo_4bit.py" code, and I get the error below:

```
$ python examples/web_demo_4bit.py --folder /home/yaofeng/ai-models/modelscope/Shanghai_AI_Laboratory/internlm-xcomposer-7b-4bit
/home/yaofeng/miniconda3/lib/python3.11/site-packages/gradio/components/button.py:89: UserWarning: Using the update method is deprecated. Simply return a new object instead, e.g. `return gr.Button(...)` instead of `return gr.Button.update(...)`.
  warnings.warn(
Init VIT ... Done
Init Perceive Sampler ... Done
Init InternLM ... Done
InternLMXComposerQForCausalLM hasn't fused attention module yet, will skip inject fused attention.
InternLMXComposerQForCausalLM hasn't fused mlp module yet, will skip inject fused mlp.
Traceback (most recent call last):
  File "/home/yaofeng/workspace/opensource/ai/lm/InternLM-XComposer/examples/web_demo_4bit.py", line 845, in <module>
    demo_ui = Demo_UI(args.folder)
              ^^^^^^^^^^^^^^^^^^^^
  File "/home/yaofeng/workspace/opensource/ai/lm/InternLM-XComposer/examples/web_demo_4bit.py", line 68, in __init__
    tokenizer = AutoTokenizer.from_pretrained(folder, trust_remote_code=True)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaofeng/miniconda3/lib/python3.11/site-packages/transformers/models/auto/tokenization_auto.py", line 755, in from_pretrained
    return tokenizer_class.from_pretrained(pretrained_model_name_or_path, *inputs, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaofeng/miniconda3/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2024, in from_pretrained
    return cls._from_pretrained(
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaofeng/miniconda3/lib/python3.11/site-packages/transformers/tokenization_utils_base.py", line 2256, in _from_pretrained
    tokenizer = cls(*init_inputs, **init_kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/yaofeng/.cache/huggingface/modules/transformers_modules/internlm-xcomposer-7b-4bit/tokenization_InternLM_XComposer.py", line 66, in __init__
    super().__init__(
  File "/home/yaofeng/miniconda3/lib/python3.11/site-packages/transformers/tokenization_utils.py", line 367, in __init__
    self._add_tokens(
  File "/home/yaofeng/miniconda3/lib/python3.11/site-packages/transformers/tokenization_utils.py", line 467, in _add_tokens
    current_vocab = self.get_vocab().copy()
                    ^^^^^^^^^^^^^^^^
  File "/home/yaofeng/.cache/huggingface/modules/transformers_modules/internlm-xcomposer-7b-4bit/tokenization_InternLM_XComposer.py", line 106, in get_vocab
    vocab = {self.convert_ids_to_tokens(i): i for i in range(self.vocab_size)}
                                                             ^^^^^^^^^^^^^^^
  File "/home/yaofeng/.cache/huggingface/modules/transformers_modules/internlm-xcomposer-7b-4bit/tokenization_InternLM_XComposer.py", line 94, in vocab_size
    return self.sp_model.get_piece_size()
           ^^^^^^^^^^^^^
AttributeError: 'InternLMXComposerTokenizer' object has no attribute 'sp_model'
```

**Comment by myownskyW7** [comment]
@yaofeng Have you successfully downloaded the tokenizer? Please see here https://github.com/InternLM/InternLM-XComposer/issues/33#issuecomment-1759152013
