### ISSUE TITLE
Something wrong when running transformers

### ISSUE THREAD

**Issue by computerfix** [InternLM/InternLM-XComposer#97]
<img width="910" alt="截屏2023-12-12 20 46 36" src="https://github.com/InternLM/InternLM-XComposer/assets/114480768/a3c62075-456a-46f7-ae8f-39ef5eeebc0d">
Traceback (most recent call last):
  File "/LLaVA/ShareGPT4V_demo.py", line 208, in <module>
    tokenizer, model, image_processor, context_len = load_pretrained_model(
  File "/LLaVA/llava/model/builder.py", line 105, in load_pretrained_model
    tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False)
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 667, in from_pretrained
    config = AutoConfig.from_pretrained(
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 998, in from_pretrained
    config_class = CONFIG_MAPPING[config_dict["model_type"]]
  File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 710, in __getitem__
    raise KeyError(key)
KeyError: 'clip_vision_model'

**Comment by xiaoachen98** [comment]
> <img alt="截屏2023-12-12 20 46 36" width="910" src="https://private-user-images.githubusercontent.com/114480768/289863115-a3c62075-456a-46f7-ae8f-39ef5eeebc0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTMwNTEsIm5iZiI6MTcwMjM5Mjc1MSwicGF0aCI6Ii8xMTQ0ODA3NjgvMjg5ODYzMTE1LWEzYzYyMDc1LTQ1NmEtNDZmNy1hZThmLTM5ZWY1ZWVlYmMwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQxNDUyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDVlYmU5OWE5ZGZhNmU3NGFmOGZlMjcwMjVkZTZkNWRjY2NmNjU3Mjc1MTJkZWE0NTNiYjRmZjllYTJmMzExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CnJGvcsV8NB02QjCLsg1q-7VMSnbyo-CZtSpiQySS-8"> Traceback (most recent call last): File "/LLaVA/ShareGPT4V_demo.py", line 208, in tokenizer, model, image_processor, context_len = load_pretrained_model( File "/LLaVA/llava/model/builder.py", line 105, in load_pretrained_model tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False) File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 667, in from_pretrained config = AutoConfig.from_pretrained( File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 998, in from_pretrained config_class = CONFIG_MAPPING[config_dict["model_type"]] File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 710, in __getitem__ raise KeyError(key) KeyError: 'clip_vision_model'

You should specify the mode-path arg with "Lin-Chen/ShareGPT4V-7B" rather than "Lin-Chen/ShareGPT4V-7B_Pretrained_vit-large336-l12". Because the letter path is for the vision encoder only.

**Comment by computerfix** [comment]
> > <img alt="截屏2023-12-12 20 46 36" width="910" src="https://private-user-images.githubusercontent.com/114480768/289863115-a3c62075-456a-46f7-ae8f-39ef5eeebc0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTMwNTEsIm5iZiI6MTcwMjM5Mjc1MSwicGF0aCI6Ii8xMTQ0ODA3NjgvMjg5ODYzMTE1LWEzYzYyMDc1LTQ1NmEtNDZmNy1hZThmLTM5ZWY1ZWVlYmMwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQxNDUyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDVlYmU5OWE5ZGZhNmU3NGFmOGZlMjcwMjVkZTZkNWRjY2NmNjU3Mjc1MTJkZWE0NTNiYjRmZjllYTJmMzExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CnJGvcsV8NB02QjCLsg1q-7VMSnbyo-CZtSpiQySS-8"> Traceback (most recent call last): File "/LLaVA/ShareGPT4V_demo.py", line 208, in tokenizer, model, image_processor, context_len = load_pretrained_model( File "/LLaVA/llava/model/builder.py", line 105, in load_pretrained_model tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False) File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 667, in from_pretrained config = AutoConfig.from_pretrained( File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 998, in from_pretrained config_class = CONFIG_MAPPING[config_dict["model_type"]] File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 710, in **getitem** raise KeyError(key) KeyError: 'clip_vision_model'
> 
> You should specify the mode-path arg with "Lin-Chen/ShareGPT4V-7B" rather than "Lin-Chen/ShareGPT4V-7B_Pretrained_vit-large336-l12". Because the letter path is for the vision encoder only.

I want to test the pretained model. Can u release the complete model configuration？Thanks!

**Comment by computerfix** [comment]
> > <img alt="截屏2023-12-12 20 46 36" width="910" src="https://private-user-images.githubusercontent.com/114480768/289863115-a3c62075-456a-46f7-ae8f-39ef5eeebc0d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTEiLCJleHAiOjE3MDIzOTMwNTEsIm5iZiI6MTcwMjM5Mjc1MSwicGF0aCI6Ii8xMTQ0ODA3NjgvMjg5ODYzMTE1LWEzYzYyMDc1LTQ1NmEtNDZmNy1hZThmLTM5ZWY1ZWVlYmMwZC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBSVdOSllBWDRDU1ZFSDUzQSUyRjIwMjMxMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDIzMTIxMlQxNDUyMzFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNDVlYmU5OWE5ZGZhNmU3NGFmOGZlMjcwMjVkZTZkNWRjY2NmNjU3Mjc1MTJkZWE0NTNiYjRmZjllYTJmMzExJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CnJGvcsV8NB02QjCLsg1q-7VMSnbyo-CZtSpiQySS-8"> Traceback (most recent call last): File "/LLaVA/ShareGPT4V_demo.py", line 208, in tokenizer, model, image_processor, context_len = load_pretrained_model( File "/LLaVA/llava/model/builder.py", line 105, in load_pretrained_model tokenizer = AutoTokenizer.from_pretrained(model_path, use_fast=False) File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/tokenization_auto.py", line 667, in from_pretrained config = AutoConfig.from_pretrained( File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 998, in from_pretrained config_class = CONFIG_MAPPING[config_dict["model_type"]] File "/opt/conda/envs/llava/lib/python3.10/site-packages/transformers/models/auto/configuration_auto.py", line 710, in **getitem** raise KeyError(key) KeyError: 'clip_vision_model'
> 
> You should specify the mode-path arg with "Lin-Chen/ShareGPT4V-7B" rather than "Lin-Chen/ShareGPT4V-7B_Pretrained_vit-large336-l12". Because the letter path is for the vision encoder only.

I want to test the pretained model. Can u release the complete model configuration？Thanks!
